# Generated by Django 3.2.10 on 2024-03-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
    ]
