# Generated by Django 3.2.10 on 2024-03-16 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20240316_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='business_description',
            new_name='business_details',
        ),
    ]
