# Generated by Django 3.2.10 on 2024-03-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shipping_Through', models.CharField(choices=[('TRACKON', 'TRACKON'), ('DTDC', 'DTDC'), ('SPEED POST', 'SPEED POST'), ('PROFESSIONAL', 'PROFESSIONAL')], max_length=15)),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Pin_Code', models.IntegerField(blank=True, null=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=250, null=True)),
                ('Consignment', models.CharField(blank=True, choices=[('Document', 'Document'), ('Non Document', 'Non Document')], max_length=20, null=True)),
                ('Content_Type', models.CharField(blank=True, choices=[('ARTIFICIAL JWELLARY', 'ARTIFICIAL JWELLARY'), ('BAGS', 'BAGS'), ('BOOKS', 'BOOKS'), ('CLOTHING', 'CLOTHING'), ('CORPORATE GIFTS', 'CORPORATE GIFTS'), ('LUGGAGE', 'LUGGAGE'), ('PERFUMES', 'PERFUMES'), ('PHOTO FRAME', 'PHOTO FRAME'), ('RAKHI', 'RAKHI'), ('SHOES', 'SHOES'), ('SLIPPERS', 'SLIPPERS')], max_length=20, null=True)),
                ('Number_of_box', models.IntegerField(blank=True, null=True)),
                ('Declared_value', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
