# Generated by Django 3.2.10 on 2024-03-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_shippingregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Message',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Mobile',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='shippingregistration',
            name='Address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='shippingregistration',
            name='City',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='shippingregistration',
            name='Consignment',
            field=models.CharField(blank=True, choices=[('Document', 'Document'), ('Non Document', 'Non Document')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingregistration',
            name='Declared_value',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='shippingregistration',
            name='Mobile',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='shippingregistration',
            name='Name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingregistration',
            name='Number_of_box',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='shippingregistration',
            name='Pin_Code',
            field=models.IntegerField(blank=True),
        ),
    ]
