# Generated by Django 3.2.10 on 2024-03-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20240316_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Mobile',
            field=models.IntegerField(),
        ),
    ]
