# Generated by Django 3.2.10 on 2024-03-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_contactus_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingregistration',
            name='Mobile',
            field=models.IntegerField(),
        ),
    ]
