# Generated by Django 3.2.10 on 2024-03-18 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_shippingregistration_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.customuser'),
        ),
    ]
