# Generated by Django 3.2.10 on 2024-03-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20240319_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingregistration',
            name='Consignment',
            field=models.CharField(blank=True, choices=[('Document', 'Document'), ('Non-Document', 'Non-Document')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shippingregistration',
            name='Content_Type',
            field=models.CharField(blank=True, choices=[('ARTIFICIAL JWELLERY', 'ARTIFICIAL JWELLERY'), ('BAGS', 'BAGS'), ('BOOKS', 'BOOKS'), ('CLOTHING', 'CLOTHING'), ('CORPORATE GIFTS', 'CORPORATE GIFTS'), ('LUGGAGE', 'LUGGAGE'), ('PERFUMES', 'PERFUMES'), ('PHOTO FRAME', 'PHOTO FRAME'), ('RAKHI', 'RAKHI'), ('SHOES', 'SHOES'), ('SLIPPERS', 'SLIPPERS')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shippingregistration',
            name='Declared_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingregistration',
            name='Number_of_box',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
