# Generated by Django 3.2.10 on 2024-03-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20240319_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingregistration',
            name='Consignment',
            field=models.CharField(choices=[('Document', 'Document'), ('Non-Document', 'Non-Document')], max_length=20),
        ),
    ]
