# Generated by Django 3.2.10 on 2024-03-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_alter_shippingregistration_consignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingregistration',
            name='Content_Type',
            field=models.CharField(blank=True, choices=[('ARTIFICIAL JWELLERY', 'ARTIFICIAL JWELLERY'), ('BAGS', 'BAGS'), ('BOOKS', 'BOOKS'), ('CLOTHING', 'CLOTHING'), ('CORPORATE GIFTS (EG:MOMENTOES/WOODEN PLAQUES)', 'CORPORATE GIFTS (EG:MOMENTOES/WOODEN PLAQUES)'), ('LUGGAGE', 'LUGGAGE'), ('PERFUMES', 'PERFUMES'), ('PHOTO FRAME', 'PHOTO FRAME'), ('RAKHI', 'RAKHI'), ('SHOES', 'SHOES'), ('SLIPPERS', 'SLIPPERS')], max_length=200, null=True),
        ),
    ]
