# Generated by Django 3.2.10 on 2024-03-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_shippingregistration_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingregistration',
            name='Declared_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shippingregistration',
            name='Number_of_box',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
