# Generated by Django 3.2.10 on 2024-03-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20240320_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingregistration',
            name='Declared_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingregistration',
            name='Number_of_box',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
