# Generated by Django 3.2.10 on 2024-04-01 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_shippingregistrationnotification_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingregistration',
            old_name='Name',
            new_name='Reciepient_Name',
        ),
    ]
