# Generated by Django 3.2.10 on 2024-04-01 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_rename_name_shippingregistration_reciepient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Placed', 'Placed'), ('Picked', 'Picked'), ('Shipped', 'Shipped'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered')], max_length=20)),
                ('Placed_updated_at', models.DateTimeField(blank=True, null=True)),
                ('Picked_updated_at', models.DateTimeField(blank=True, null=True)),
                ('Shipped_updated_at', models.DateTimeField(blank=True, null=True)),
                ('Delivered_updated_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.shippingregistration')),
            ],
        ),
    ]
