# Generated by Django 3.2.10 on 2024-04-04 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_trackingstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackingstatus',
            old_name='Picked_updated_at',
            new_name='Collected_updated_at',
        ),
    ]
