# Generated by Django 3.2.10 on 2024-04-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_auto_20240404_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingregistration',
            name='Registration_status',
        ),
        migrations.AddField(
            model_name='shippingregistration',
            name='registration_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, null=True),
        ),
    ]
