# Generated by Django 3.2.10 on 2024-04-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_alter_shippingregistration_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingregistration',
            name='last_update_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
