# Generated by Django 3.2.10 on 2024-04-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_remove_shippingregistration_last_update_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='billings',
            name='packing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billings',
            name='packing_cover',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
