# Generated by Django 3.2.10 on 2024-04-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_auto_20240412_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingstatus',
            name='Returned_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackingstatus',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Collected', 'Collected'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], max_length=20),
        ),
    ]
