# Generated by Django 3.2.10 on 2024-04-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_auto_20240412_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='billings',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='billings',
            name='Price_per_kg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='billings',
            name='Total_weight',
            field=models.FloatField(),
        ),
    ]
