# Generated by Django 3.2.10 on 2024-04-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_auto_20240412_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingregistration',
            name='Price_per_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingregistration',
            name='Total_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingregistration',
            name='Total_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingregistration',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shippingregistration',
            name='packing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingregistration',
            name='packing_cover',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
