# Generated by Django 3.2.10 on 2024-04-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_auto_20240412_1237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billings',
        ),
    ]
