# Generated by Django 3.2.10 on 2024-04-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0048_auto_20240413_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
