# Generated by Django 3.2.10 on 2024-04-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_adminlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlogin',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
