# Generated by Django 3.2.10 on 2024-04-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_auto_20240415_1449'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminLogin',
        ),
    ]
