# Generated by Django 3.2.10 on 2024-04-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_adminuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
