# Generated by Django 3.2.10 on 2024-05-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_shippingregistration_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_secret_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
