# Generated by Django 3.2.10 on 2024-05-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_customuser_otp_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingregistration',
            name='Address',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
