# Generated by Django 3.2.10 on 2024-05-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_alter_shippingregistration_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingregistration',
            name='Shipping_Through',
            field=models.CharField(choices=[('TRACKON', 'TRACKON'), ('DTDC', 'DTDC'), ('SPEED POST', 'SPEED POST'), ('PROFESSIONAL', 'PROFESSIONAL')], max_length=15, null=True),
        ),
    ]
